/*
    通用表单验证方法
    Validform version 3.0
    For more information, you can visit www.rjboy.cn
    By sean during April 7, 2010 - August 7, 2011
*/

(function($){var errorobj=null,msgobj,msghidden=true,tipmsg={w:"请输入正确信息！",r:"通过信息验证！",c:"正在检测信息…",s:"请填入信息！",v:"所填信息没有经过验证，请稍后…",p:"正在提交数据…",err:"提交数据出错，请检查地址是否正确！"},creatMsgbox=function(){if($("#Validform_msg").length!==0){return false;}
msgobj=$('<div id="Validform_msg"><div class="Validform_title">提示信息<a class="Validform_close" href="javascript:void(0);">&chi;</a></div><div class="Validform_info"></div><div class="iframe"><iframe frameborder="0" scrolling="no" height="100%" width="100%"></iframe></div></div>').appendTo("body");msgobj.find("a.Validform_close").click(function(){msgobj.hide();msghidden=true;if(errorobj){errorobj.focus().addClass("Validform_error");}
return false;}).focus(function(){this.blur();});$(window).bind("scroll resize",function(){if(!msghidden){var left=($(window).width()-msgobj.width())/2,top=($(window).height()-msgobj.height())/2,topTo=(document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop)+(top>0?top:0);msgobj.animate({left:left,top:topTo},{duration:400,queue:false});}});};$.fn.Validform=function(settings){var defaults={};settings=$.extend({},$.fn.Validform.sn.defaults,settings);settings.datatype&&$.extend($.Datatype,settings.datatype);this.each(function(){var $this=$(this);var posting=false;$this.find("[tip]").each(function(){var defaultvalue=$(this).attr("tip");var altercss=$(this).attr("altercss");$(this).focus(function(){if($(this).val()==defaultvalue){$(this).val('');if(altercss){$(this).removeClass(altercss);}}}).blur(function(){if($.trim($(this).val())===''){$(this).val(defaultvalue);if(altercss){$(this).addClass(altercss);}}});});$this.find("[datatype]").blur(function(){var flag=true;flag=$.fn.Validform.sn.checkform($(this),$this,{type:settings.tiptype,sweep:settings.tipSweep},"hide");if(!flag){return false;}
if(typeof(flag)!="boolean"){$(this).removeClass("Validform_error");return false;}
flag=$.fn.Validform.sn.regcheck($(this).attr("datatype"),$(this).val());if(!flag){if($(this).attr("ignore")==="ignore"&&($(this).val()===""||$(this).val()===$(this).attr("tip"))){if(settings.tiptype==2){$(this).parent().next().find(".Validform_checktip").removeClass().addClass("Validform_checktip").text("");}else if(typeof settings.tiptype=="function"){(settings.tiptype)("",{obj:$(this),type:4},$.fn.Validform.sn.cssctl);}
flag=true;errorobj=null;return true;}
errorobj=$(this);$.fn.Validform.sn.showmsg($(this).attr("errormsg")||tipmsg.w,settings.tiptype,{obj:$(this),sweep:settings.tipSweep},"hide");}else{if($(this).attr("ajaxurl")){var inputobj=$(this);inputobj.attr("valid",tipmsg.c);$.fn.Validform.sn.showmsg(tipmsg.c,settings.tiptype,{obj:inputobj,type:1,sweep:settings.tipSweep},"hide");$.ajax({type:"POST",url:inputobj.attr("ajaxurl"),data:"param="+$(this).val()+"&name="+$(this).attr("name"),dataType:"text",success:function(s){if(s=="y"){inputobj.attr("valid","true");errorobj=null;$.fn.Validform.sn.showmsg(tipmsg.r,settings.tiptype,{obj:inputobj,type:2,sweep:settings.tipSweep},"hide");}else{inputobj.attr("valid",s);errorobj=inputobj;$.fn.Validform.sn.showmsg(s,settings.tiptype,{obj:inputobj,sweep:settings.tipSweep});}},error:function(){inputobj.attr("valid",tipmsg.err);errorobj=inputobj;$.fn.Validform.sn.showmsg(tipmsg.err,settings.tiptype,{obj:inputobj,sweep:settings.tipSweep});}});}else{errorobj=null;$.fn.Validform.sn.showmsg(tipmsg.r,settings.tiptype,{obj:$(this),type:2,sweep:settings.tipSweep},"hide");}}});$this.find(":checkbox[datatype],:radio[datatype]").each(function(){var _this=$(this);var name=_this.attr("name");$this.find("[name="+name+"]").filter(":checkbox,:radio").not("[datatype]").bind("blur",function(){_this.trigger("blur");});});var subform=function(){var flag=true;if(posting){return false;}
$this.find("[datatype]").each(function(){flag=$.fn.Validform.sn.checkform($(this),$this,{type:settings.tiptype,sweep:settings.tipSweep});if(!flag){errorobj.focus();return false;}
if(typeof(flag)!="boolean"){flag=true;return true;}
flag=$.fn.Validform.sn.regcheck($(this).attr("datatype"),$(this).val());if(!flag){if($(this).attr("ignore")==="ignore"&&($(this).val()===""||$(this).val()===$(this).attr("tip"))){flag=true;errorobj=null;return true;}
errorobj=$(this);errorobj.focus();$.fn.Validform.sn.showmsg($(this).attr("errormsg")||tipmsg.w,settings.tiptype,{obj:$(this),sweep:settings.tipSweep});return false;}
if($(this).attr("ajaxurl")){if($(this).attr("valid")!="true"){flag=false;var thisobj=$(this);errorobj=thisobj;errorobj.focus();$.fn.Validform.sn.showmsg(thisobj.attr("valid")||tipmsg.v,settings.tiptype,{obj:thisobj,sweep:settings.tipSweep});if(!msghidden||settings.tiptype!=1){setTimeout(function(){thisobj.trigger("blur");},2000);}
return false;}else{$.fn.Validform.sn.showmsg(tipmsg.r,settings.tiptype,{obj:$(this),type:2,sweep:settings.tipSweep},"hide");flag=true;}}});if(flag&&!posting){errorobj=null;if(settings.postonce){posting=true;}
if(settings.ajaxPost){$.fn.Validform.sn.showmsg(tipmsg.p,settings.tiptype,{type:1,sweep:settings.tipSweep},"alwaysshow");$.ajax({type:"POST",dataType:"json",url:$this.attr("action"),data:$this.serialize(),success:function(data){$.fn.Validform.sn.showmsg(data.info,settings.tiptype,{type:2,sweep:settings.tipSweep},"alwaysshow");settings.callback&&(settings.callback)(data);},error:function(){$.fn.Validform.sn.showmsg(tipmsg.err,settings.tiptype,{type:3,sweep:settings.tipSweep},"alwaysshow");}});return false;}else{settings.callback?(settings.callback)():$this.get(0).submit();}}};settings.btnSubmit&&$this.find(settings.btnSubmit).bind("click",subform);$this.submit(function(){subform();return false;});});if(settings.tiptype==1||(settings.tiptype==2&&settings.ajaxPost)){creatMsgbox();}};$.fn.Validform.sn={defaults:{tiptype:1,tipSweep:false,postonce:false,ajaxPost:false},toString:Object.prototype.toString,regcheck:function(type,gets){if(!(type in $.Datatype)){var mac=type.match($.Datatype["match"]),temp;reg:for(var name in $.Datatype){temp=name.match($.Datatype["match"]);if(!temp){continue reg;}
if(mac[1]===temp[1]){var str=$.Datatype[name].toString();var regxp=new RegExp("\\{"+temp[2]+","+temp[3]+"\\}");str=str.replace(regxp,"{"+mac[2]+","+mac[3]+"}").replace(/^\//,"").replace(/\/$/,"");$.Datatype[type]=new RegExp(str);break reg;}}}
if(this.toString.call($.Datatype[type])=="[object RegExp]"){return $.Datatype[type].test(gets);}
return false;},showmsg:function(msg,type,o,show){if(errorobj){errorobj.addClass("Validform_error");}
if(typeof type=="function"){if(!(o.sweep&&show=="hide")){(type)(msg,o,this.cssctl);}
return false;}
if(type==1||show=="alwaysshow"){msgobj.find(".Validform_info").text(msg);}
if(type==1&&show!="hide"||show=="alwaysshow"){msghidden=false;msgobj.find(".iframe").css("height",msgobj.height());var left=($(window).width()-msgobj.width())/2;var top=($(window).height()-msgobj.height())/2;top=(document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop)+(top>0?top:0);msgobj.css({"left":left}).show().animate({top:top},100);}
if(type==2){o.obj.parent().next().find(".Validform_checktip").text(msg);this.cssctl(o.obj.parent().next().find(".Validform_checktip"),o.type);}},checkform:function(obj,parentobj,tiptype,show){var errormsg=obj.attr("errormsg")||tipmsg.w,inputname;if(obj.is("[datatype='radio']")){inputname=obj.attr("name");var radiovalue=parentobj.find(":radio[name="+inputname+"]:checked").val();if(!radiovalue){errorobj=obj;this.showmsg(errormsg,tiptype.type,{obj:obj,sweep:tiptype.sweep},show);return false;}
errorobj=null;this.showmsg(tipmsg.r,tiptype.type,{obj:obj,type:2,sweep:tiptype.sweep},"hide");return"radio";}
if(obj.is("[datatype='checkbox']")){inputname=obj.attr("name");var checkboxvalue=parentobj.find(":checkbox[name="+inputname+"]:checked").val();if(!checkboxvalue){errorobj=obj;this.showmsg(errormsg,tiptype.type,{obj:obj,sweep:tiptype.sweep},show);return false;}
errorobj=null;this.showmsg(tipmsg.r,tiptype.type,{obj:obj,type:2,sweep:tiptype.sweep},"hide");return"checkbox";}
if(obj.is("[datatype='select']")){if(!obj.val()){errorobj=obj;this.showmsg(errormsg,tiptype.type,{obj:obj,sweep:tiptype.sweep},show);return false;}
errorobj=null;this.showmsg(tipmsg.r,tiptype.type,{obj:obj,type:2,sweep:tiptype.sweep},"hide");return"select";}
var defaultvalue=obj.attr("tip");if((obj.val()===""||obj.val()===defaultvalue)&&obj.attr("ignore")!="ignore"){errorobj=obj;this.showmsg(obj.attr("nullmsg")||tipmsg.s,tiptype.type,{obj:obj,sweep:tiptype.sweep},show);return false;}
if(obj.attr("recheck")){var theother=parentobj.find("input[name="+obj.attr("recheck")+"]:first");if(obj.val()!=theother.val()){errorobj=obj;this.showmsg(errormsg,tiptype.type,{obj:obj,sweep:tiptype.sweep},show);return false;}}
obj.removeClass("Validform_error");errorobj=null;return true;},cssctl:function(obj,status){switch(status){case 1:obj.removeClass("Validform_right Validform_wrong").addClass("Validform_checktip Validform_loading");break;case 2:obj.removeClass("Validform_wrong Validform_loading").addClass("Validform_checktip Validform_right");break;case 4:obj.removeClass("Validform_right Validform_wrong Validform_loading").addClass("Validform_checktip");break;default:obj.removeClass("Validform_right Validform_loading").addClass("Validform_checktip Validform_wrong");}}};$.Showmsg=function(msg){creatMsgbox();$.fn.Validform.sn.showmsg(msg,1);};$.Hidemsg=function(){msgobj.hide();msghidden=true;};$.Datatype={"match":/^(.+)(\d+)-(\d+)$/,"*":/^[^\s]+$/,"*6-16":/^[^\s]{6,16}$/,"n":/^\d+$/,"s":/^[\u4E00-\u9FA5\uf900-\ufa2d\w]+$/,"s6-18":/^[\u4E00-\u9FA5\uf900-\ufa2d\w]{6,18}$/,"p":/^[0-9]{6}$/,"m":/^13[0-9]{9}$|15[0-9]{9}$|18[0-9]{9}$/,"e":/^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/};})(jQuery);